### PR TITLE
fix: Func missing order authtoken parameters

### PR DESCRIPTION
**Pull request by LZiHaN**
In the three files, the lack of some parameters of the related order function will cause an error to be reported, and I have added the relevant parameters.

### CODE REVIEW

**Comment by LZiHaN** [comment]
func (c *Client) GetOrder(orderID string, authToken *string) (*Order, error)

**Comment by LZiHaN** [comment]
Hey @im2nguyen, I had a pr  that  this change fixed it.

**Comment by im2nguyen** [comment]
Hey @LZiHaN, thank you for submitting this PR! Were you able to test this locally?

@hashicorp/terraform-education can you verify and merge this?

**Comment by LZiHaN** [comment]
Yes, after I modified it, the local test passed. @im2nguyen

**Comment by LZiHaN** [comment]
@im2nguyen,see [https://github.com/hashicorp/terraform-provider-hashicups/issues/77](https://github.com/hashicorp/terraform-provider-hashicups/issues/77)

**Review by im2nguyen — COMMENTED** [review]
I installed and tested this locally -- can confirm it works. 

@LZiHaN, can you also use this as an opportunity to update the `examples` directory? I don't believe `versions` is support any longer...

so I would replace `versions = ["0.3.0"]` with `version = "0.3.1"` in both `examples/main.tf` and `examples/coffee/main.tf`.

Once you do that, I can approve this PR, but @hashicorp/terraform-education is responsible for merging this PR. They may need to update some tutorials to reflect these changes

Thank you again for contributing!! 😄

**Review by im2nguyen — COMMENTED** [review]
@LZiHaN we also need to update `examples/import/main.tf` to point to `0.3.1`

**Comment by LZiHaN** [comment]
@im2nguyen ,sorry,English is not my native language, so I used "DEPRECATED" incorrectly.Now I updated the examples directory.I tested this locally.
image

**Review by im2nguyen — APPROVED** [review]
This looks perfect, thanks @LZiHaN!!

Don't worry about the `deprecated` label, I understood what you meant 😄

**Comment by LZiHaN** [comment]
Thank you. @im2nguyen

**Comment by judithpatudith** [comment]
Thank you @LZiHaN and @im2nguyen!

**Pull request merged**
